// Code generated by "stringer -type=DialogType -trimprefix=D"; DO NOT EDIT.

package mtpwrap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DUnknown-0]
	_ = x[DGroup-1]
	_ = x[DMegagroup-2]
	_ = x[DGigagroup-3]
	_ = x[DChannel-4]
}

const _DialogType_name = "UnknownGroupMegagroupGigagroupChannel"

var _DialogType_index = [...]uint8{0, 7, 12, 21, 30, 37}

func (i DialogType) String() string {
	if i < 0 || i >= DialogType(len(_DialogType_index)-1) {
		return "DialogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DialogType_name[_DialogType_index[i]:_DialogType_index[i+1]]
}
